version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./.docker/postgres/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
        - "27017:27017"

  broker:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure

  web:
    build: .
    entrypoint: /entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    image: web-app-image
    ports:
      - "8000:8000"
    depends_on:
      - db
      - broker
      - mongo
    links: 
      - mongo

  celery_worker:
    command: sh -c "celery -A backend.core.celery worker -l info"
    container_name: celery_worker
    depends_on:
      - web
      - db
      - broker
    hostname: celery_worker
    image: web-app-image
    restart: on-failure

  celery_beat:
    command: sh -c "celery -A backend.core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    container_name: celery_beat
    depends_on:
      - web
      - db
      - broker
    image: web-app-image
    restart: on-failure