# Generated by Django 3.1.7 on 2021-03-23 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('tar_included', models.BooleanField()),
                ('subscription', models.FloatField()),
                ('cycle', models.CharField(choices=[('W', 'Weekly'), ('D', 'Daily')], max_length=1)),
                ('type', models.CharField(choices=[('bi', 'bi-time'), ('tri', 'tri-time'), ('simple', 'simple')], max_length=6)),
                ('offer_iva', models.BooleanField()),
                ('off_peak_price', models.FloatField()),
                ('peak_price', models.FloatField()),
                ('unit', models.CharField(choices=[('KWH', 'kwh'), ('MIN', 'min')], max_length=3)),
                ('valid', models.BooleanField()),
                ('publish', models.BooleanField()),
                ('vat', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('owner', models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
