# Generated by Django 3.0.5 on 2021-03-25 04:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('tar_included', models.BooleanField()),
                ('subscription', models.FloatField()),
                ('cycle', models.CharField(choices=[('W', 'Weekly'), ('D', 'Daily')], max_length=1)),
                ('type', models.CharField(choices=[('bi', 'bi-time'), ('tri', 'tri-time'), ('simple', 'simple')], max_length=6)),
                ('offer_iva', models.BooleanField()),
                ('off_peak_price', models.FloatField()),
                ('peak_price', models.FloatField()),
                ('unit', models.CharField(choices=[('KWH', 'kwh'), ('MIN', 'min')], max_length=3)),
                ('valid', models.BooleanField()),
                ('publish', models.BooleanField()),
                ('vat', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
