# Generated by Django 3.1.7 on 2021-03-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularplans', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regularplans',
            field=models.ManyToManyField(to='regularplans.RegularPlan'),
        ),
    ]
