# Generated by Django 3.1.7 on 2021-03-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='regularplans',
        ),
    ]
